/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAlvosRouteImport } from './routes/_authenticated/alvos'
import { Route as AuthenticatedAdminIngestionRouteImport } from './routes/_authenticated/admin/ingestion'
import { Route as ApiPublicIngestionTickRouteImport } from './routes/api/public/ingestion/tick'
import { Route as ApiPublicDiscoveryRefreshRouteImport } from './routes/api/public/discovery/refresh'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlvosRoute = AuthenticatedAlvosRouteImport.update({
  id: '/alvos',
  path: '/alvos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIngestionRoute =
  AuthenticatedAdminIngestionRouteImport.update({
    id: '/admin/ingestion',
    path: '/admin/ingestion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicIngestionTickRoute = ApiPublicIngestionTickRouteImport.update({
  id: '/api/public/ingestion/tick',
  path: '/api/public/ingestion/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscoveryRefreshRoute =
  ApiPublicDiscoveryRefreshRouteImport.update({
    id: '/api/public/discovery/refresh',
    path: '/api/public/discovery/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alvos': typeof AuthenticatedAlvosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/api/public/discovery/refresh': typeof ApiPublicDiscoveryRefreshRoute
  '/api/public/ingestion/tick': typeof ApiPublicIngestionTickRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alvos': typeof AuthenticatedAlvosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/api/public/discovery/refresh': typeof ApiPublicDiscoveryRefreshRoute
  '/api/public/ingestion/tick': typeof ApiPublicIngestionTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/alvos': typeof AuthenticatedAlvosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/api/public/discovery/refresh': typeof ApiPublicDiscoveryRefreshRoute
  '/api/public/ingestion/tick': typeof ApiPublicIngestionTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/alvos'
    | '/configuracoes'
    | '/admin/ingestion'
    | '/api/public/discovery/refresh'
    | '/api/public/ingestion/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/alvos'
    | '/configuracoes'
    | '/'
    | '/admin/ingestion'
    | '/api/public/discovery/refresh'
    | '/api/public/ingestion/tick'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/alvos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/'
    | '/_authenticated/admin/ingestion'
    | '/api/public/discovery/refresh'
    | '/api/public/ingestion/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicDiscoveryRefreshRoute: typeof ApiPublicDiscoveryRefreshRoute
  ApiPublicIngestionTickRoute: typeof ApiPublicIngestionTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alvos': {
      id: '/_authenticated/alvos'
      path: '/alvos'
      fullPath: '/alvos'
      preLoaderRoute: typeof AuthenticatedAlvosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ingestion': {
      id: '/_authenticated/admin/ingestion'
      path: '/admin/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AuthenticatedAdminIngestionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/ingestion/tick': {
      id: '/api/public/ingestion/tick'
      path: '/api/public/ingestion/tick'
      fullPath: '/api/public/ingestion/tick'
      preLoaderRoute: typeof ApiPublicIngestionTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discovery/refresh': {
      id: '/api/public/discovery/refresh'
      path: '/api/public/discovery/refresh'
      fullPath: '/api/public/discovery/refresh'
      preLoaderRoute: typeof ApiPublicDiscoveryRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlvosRoute: typeof AuthenticatedAlvosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminIngestionRoute: typeof AuthenticatedAdminIngestionRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlvosRoute: AuthenticatedAlvosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminIngestionRoute: AuthenticatedAdminIngestionRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicDiscoveryRefreshRoute: ApiPublicDiscoveryRefreshRoute,
  ApiPublicIngestionTickRoute: ApiPublicIngestionTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
